2024-05-19 22:36:57,384 INFO    Thread-5 (_run_job):12294 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-19 22:36:57,384 INFO    Thread-5 (_run_job):12294 [wandb_setup.py:_flush():76] Configure stats pid to 12294
2024-05-19 22:36:57,384 INFO    Thread-5 (_run_job):12294 [wandb_setup.py:_flush():76] Loading settings from /home/student/.config/wandb/settings
2024-05-19 22:36:57,384 INFO    Thread-5 (_run_job):12294 [wandb_setup.py:_flush():76] Loading settings from /home/student/db_hw_2/wandb/settings
2024-05-19 22:36:57,384 INFO    Thread-5 (_run_job):12294 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'db_hw_3_youngmok_kim', 'entity': 'ymkim78', 'root_dir': '/home/student/db_hw_2', 'sweep_id': 'btlo1f3x', 'run_id': 'fzab6lbg', 'sweep_param_path': '/home/student/db_hw_2/wandb/sweep-btlo1f3x/config-fzab6lbg.yaml'}
2024-05-19 22:36:57,384 INFO    Thread-5 (_run_job):12294 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-19 22:36:57,384 INFO    Thread-5 (_run_job):12294 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'continual_learning.py', 'program_abspath': '/home/student/db_hw_2/continual_learning.py', 'program': '/home/student/db_hw_2/continual_learning.py'}
2024-05-19 22:36:57,384 INFO    Thread-5 (_run_job):12294 [wandb_init.py:_log_setup():520] Logging user logs to /home/student/db_hw_2/wandb/run-20240519_223657-fzab6lbg/logs/debug.log
2024-05-19 22:36:57,384 INFO    Thread-5 (_run_job):12294 [wandb_init.py:_log_setup():521] Logging internal logs to /home/student/db_hw_2/wandb/run-20240519_223657-fzab6lbg/logs/debug-internal.log
2024-05-19 22:36:57,384 INFO    Thread-5 (_run_job):12294 [wandb_init.py:init():560] calling init triggers
2024-05-19 22:36:57,384 INFO    Thread-5 (_run_job):12294 [wandb_init.py:init():567] wandb.init called with sweep_config: {'batch_size': 32, 'classes': 10, 'epochs': 15, 'learning_rate': 0.06010982348770873}
config: {}
2024-05-19 22:36:57,384 INFO    Thread-5 (_run_job):12294 [wandb_init.py:init():605] wandb.init() called when a run is still active
2024-05-19 22:36:57,385 ERROR   Thread-5 (_run_job):12294 [wandb_init.py:init():1174] error in wandb.init()
Traceback (most recent call last):
  File "/home/student/anaconda3/envs/db_hw/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
           ^^^^^^^^^
  File "/home/student/anaconda3/envs/db_hw/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 606, in init
    with telemetry.context() as tel:
  File "/home/student/anaconda3/envs/db_hw/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/student/anaconda3/envs/db_hw/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 792, in _telemetry_callback
    self._telemetry_flush()
  File "/home/student/anaconda3/envs/db_hw/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 803, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/student/anaconda3/envs/db_hw/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 101, in _publish_telemetry
    self._publish(rec)
  File "/home/student/anaconda3/envs/db_hw/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/student/anaconda3/envs/db_hw/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "/home/student/anaconda3/envs/db_hw/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/student/anaconda3/envs/db_hw/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/student/anaconda3/envs/db_hw/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2024-05-19 22:37:03,745 INFO    MainThread:12294 [pyagent.py:run():323] Starting sweep agent: entity=None, project=None, count=10
